com:
  mqtt:
    host: tcp://47.101.180.112:1883
    clientid: duyulong
    topic: windows
    username: admin
    password: public
    timeout: 10
    keepalive: 20


spring:
  application:
    name: springboot-demo
  #redis配置
  redis:
    host: 47.101.180.112
    password: 123456
    port: 6379
    database: 1
